### ISSUE TITLE
"modprobe: module wireguard not found in modules.dep"

### ISSUE THREAD

**Issue by vsudakov** [shvchk/padavan-wireguard-client#2]
on Asus router we installed `RT-AC51U_3.4.3.9L-nukdokplex.trx` firmware from <https://bitbucket.org/padavan/rt-n56u/downloads/>

after running `/etc/storage/wireguard/client.sh start` - got the following error:

```
modprobe: module wireguard not found in modules.dep
RTNETLINK answers: Operation not supported
...
```

does it mean that my firmware doesn't support WireGuard?

Thank you!

**Comment by shvchk** [comment]
Yeah, that means your firmware doesn't support WireGuard. You need a firmware with WireGuard support, like [padavan-ng from Alexey](https://gitlab.com/dm38/padavan-ng). It could be easily built and installed with [Prometheus](http://pm.freize.net) ([support forum](https://4pda.to/forum/index.php?showtopic=714487) in Russian, but Google Translate does the job).
