### ISSUE TITLE
No internet connection, waiting...

### ISSUE THREAD

**Issue by maxfiligree** [shvchk/padavan-wireguard-client#3]
Здравствуйте, у меня возникает проблема в самом начале работы скрипта client.sh - я получаю "No internet connection, waiting..." - при этом, если я делаю ping, как в скрипте "ping -c 1 -W 1 1.1.1.1" - пинг проходит и интернет на роутере и на устройствах есть. Помогите пожалуйста разобраться, в чём причины?

**Comment by shvchk** [comment]
Не заметил ваше сообщение, прошу прощения.

Скрипт пингует ваш `$ENDPOINT_ADDR` (сервер WireGuard), указанный в `conf.sh` — возможно, он недоступен (оффлайн или фильтрует ICMP пакеты)?

**Comment by shvchk** [comment]
Закрываю из-за неактивности, если проблема всё же существует, дайте знать — переоткрою.
