### ISSUE TITLE
Трафик в обход wireguard

### ISSUE THREAD

**Issue by Kerber0ss** [shvchk/padavan-wireguard-client#6]
Здравствуйте, сейчас весь трафик заворачивается в wireguard, подскажите правила в добавок к текущим чтобы пробросить IP одного клиента обход wireguard?

**Comment by shvchk** [comment]
Для клиента с IP 192.168.X.X:
`ip rule add from 192.168.X.X table main pref 30`

Эту команду можно добавить в `Персонализация` > `Скрипты` > `Выполнить после полного запуска маршрутизатора`
